### ISSUE TITLE
テキスト部分吹き出し

### ISSUE THREAD

**Issue by IKKImt** [Club-Advance/mij#17]

**Comment by 0014ug** [comment]
(豊岡の皮革トートバッグ)
①背面は定期や小物の収納に便利な大型ポケット
②鞄がふくらまずスッキリ仕舞える適度なマチ幅
③ゴールドのさりげないエンブレムが上品
④小物の整理整頓に便利な内ポケットも充実
⑤同素材・同色のパスケース付き

(豊岡の皮革手提げ)
①上品な印象の丸みあるシンプルなシルエット
②サイドのホックで鞄がふくらまずスッキリ
③小物の整理整頓に便利な内ポケットも充実
④ゴールドのさりげないエンブレムが上品

(印伝　印鑑入れ)
①美しい発色とモダンな模様付けが上品
②使った後も汚れにくい裏ばり仕様
③チャームのような便利な朱肉付き

(印伝　小銭入れ)
①大きく開くファスナーで出し入れしやすい

(倉敷の帽子(上))
①正面は素材感のあるベルト使いで上品な印象に
②後ろはすっきりとしたシルエット

(倉敷の帽子(下))
①正面はシンプルながらもエレガンスな雰囲気
②後ろはすっきりとしたシルエット
