### ISSUE TITLE
socialpluginの情報（twitter、facebookの情報）

### ISSUE THREAD

**Issue by IKKImt** [Club-Advance/mij#9]
→twitter、facebookのリンク先
→twitter表示後のコメント
→twitter表示後のurl
→facebook表示後のurl

**Comment by 0014ug** [comment]
5）socialpluginの情報（twitter、facebookの情報）
og:title
Made in JAPAN　|　メイドインジャパン　|　イトーヨーカドー

og:description
日本の技術と心を届けるイトーヨーカドーのMade in JAPAN メイドインジャパン
